### ISSUE TITLE
Translation problem (again?)

### ISSUE THREAD

**Issue by KobaWHO** [BlockCrusader/tML-Mods#10]
Hi, for some reason the Russian translation on Github that I sent you does not match the translation in the game
In the game, half of the text is not translated into Russian, unlike the version in Github
Don't know what the problem is?

![ru-RU_Mods BInfoAcc hjson - Visual Studio Code 20 05 2024 17_23_58](https://github.com/BlockCrusader/tML-Mods/assets/170234144/899a54b1-bb66-4921-a81b-9175fbc93bc3)

**Comment by KobaWHO** [comment]
On the left in the game, on the right in Github

**Comment by BlockCrusader** [comment]
I directly downloaded the file on this GitHub repo to the mod itself, and the formatting correctly matches the English version. I'm not sure what could be going wrong.

**Comment by KobaWHO** [comment]
The problem resolved itself after reinstalling the mod.
