### ISSUE TITLE
issue on leveling mod

### ISSUE THREAD

**Issue by LearningEnjoyer777** [BlockCrusader/tML-Mods#11]
[client.log](https://github.com/user-attachments/files/15742113/client.log)

**Comment by LearningEnjoyer777** [comment]
![Снимок экрана 2024-06-07 191105](https://github.com/BlockCrusader/tML-Mods/assets/172061057/f9e5afd9-7a78-4634-9039-3b7353e87079)

here: as you can see the level cap is 5/5 with max xp when is try to get more it just resets it again without leveling up

**Comment by BlockCrusader** [comment]
Actually, your weapon's level is 0. 
The Level: 0 tooltip below '5 Evolution Points left !' is the leveling system from my mod. Weapons with a set Base XP (This Blood Butcher appears to have been properly set up, it has a base of 2000 judging by the tooltip) should gain XP from dealing damage. It doesn't look like the weapon has any XP, so if you haven't yet, go start using it in combat. I can only assume the other mods you're using grant XP by different venues.
TBH you have a TON of weapon-upgrading mods (not to mention a lot of mods in general) enabled at the same time. The log file doesn't show any errors on BSWL's end but I wouldn't be surprised if there's some compatibility issues going on here considering how many mods you have modifying weapons.

**Comment by LearningEnjoyer777** [comment]
wait so your your mod isn't the one that adds level ups that change the name of you weapon and add a +x change to the name? like in this image you can see that the weapon has a +5 in the end of its name

if its not then I'm sorry for bothering and thank you for your quick response.

**Comment by LearningEnjoyer777** [comment]
oooh never mind youre right this really isn't from your mod its from a mod RPG... ok still thanks a lot
